In [2]:
import pandas as pd

In [4]:

url = "https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv"

file = pd.read_csv(url,encoding='latin-1')

In [46]:
file.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [12]:
file.tail()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [18]:
file.groupby('Item').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [28]:
#What is the total sum of Animal Fat produced in 2014 and 2017 respectively?

In [26]:
file.groupby('Item')['Y2014'].sum()

Item
Alcohol, Non-Food        2403.00
Alcoholic Beverages    102410.11
Animal Products         11935.65
Animal fats            209460.54
Apples and products      9499.23
                         ...
Vegetables, Other      155038.96
Vegetal Products       107145.19
Wheat and products     232670.13
Wine                     4497.36
Yams                   200396.96
Name: Y2014, Length: 119, dtype: float64

In [27]:

file.groupby('Item')['Y2017'].sum()

Item
Alcohol, Non-Food        2348.00
Alcoholic Beverages     95581.06
Animal Products         11547.65
Animal fats            269617.53
Apples and products     10198.90
                         ...
Vegetables, Other      157752.59
Vegetal Products       107655.20
Wheat and products     240047.62
Wine                     4178.02
Yams                   229174.59
Name: Y2017, Length: 119, dtype: float64

In [29]:
#What is the mean and standard deviation across the whole dataset for the year 2015 to 3 decimal places?

In [33]:
file['Y2015'].mean().round(3)

135.236

In [34]:
file['Y2015'].std().round(3)

1603.404

In [38]:
file['Y2016'].isna().count()

60943

In [41]:
file.isna().mean().round(4) * 100

Area Code       0.00
Area            0.00
Item Code       0.00
Item            0.00
Element Code    0.00
Element         0.00
Unit            0.00
Y2014           2.61
Y2015           2.54
Y2016           2.52
Y2017           2.47
Y2018           2.36
dtype: float64

In [44]:
file.corr()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [45]:
#What year has the highest sum of Import Quantity?

#Hint- Perform a groupby operation on ‘Element’ and use the resulting Dataframe to answer the questio

In [52]:
file.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [49]:
file.groupby('Unit').count()

,Area Code,Area,Item Code,Item,Element Code,Element,Y2014,Y2015,Y2016,Y2017,Y2018
Unit,,,,,,,,,,,
1000 persons,45,45,45,45,45,45,45,45,45,45,45
1000 tonnes,40933,40933,40933,40933,40933,40933,39574,39585,39568,39589,39643
g/capita/day,10046,10046,10046,10046,10046,10046,9928,9945,9958,9962,9973
kcal/capita/day,5014,5014,5014,5014,5014,5014,4947,4955,4963,4965,4969
kg,4905,4905,4905,4905,4905,4905,4860,4865,4874,4876,4877

In [51]:
file.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [53]:
#What is the total number of the sum of Production in 2014? = 1931287.75

In [ ]:
#Which of these elements had the highest sum in 2018?

#Hint-  Select columns ‘Y2018’ and ‘Element’, Perform a groupby operation on ‘Element’ on the selected dataframe and answer the  question.

In [62]:
file.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [86]:
file.groupby(['Area','Element']).sum().head(10)

#import qty = 36238.29

                                             Area Code  Item Code  \
Area    Element
Algeria Domestic supply quantity                   464     311204
        Export Quantity                            392     264011
        Fat supply quantity (g/capita/day)         432     291489
        Feed                                        88      58967
        Food                                       420     282744
        Food supply (kcal/capita/day)              432     291489
        Food supply quantity (kg/capita/yr)        420     282744
        Import Quantity                            448     301030
        Losses                                     208     139857
        Other uses (non-food)                      148     101269

                                             Element Code     Y2014     Y2015  \
Area    Element
Algeria Domestic supply quantity                   614916  83755.94  85972.86
        Export Quantity                            579278   1328.64   1104.62
        Fat supply quantity (g/capita/day)          73872    320.19    317.40
        Feed                                       121462   9656.04  10308.00
        Food                                       539910  60582.69  61693.49
        Food supply (kcal/capita/day)               71712  13500.00  13512.00
        Food supply quantity (kg/capita/yr)         67725   1556.45   1552.81
        Import Quantity                            628432  34940.12  37841.91
        Losses                                     266396   7231.00   7471.00
        Other uses (non-food)                      190698   3315.22   3483.37

                                                Y2016     Y2017     Y2018
Area    Element
Algeria Domestic supply quantity             87157.61  86810.42  90023.42
        Export Quantity                       1340.22   1494.54    811.54
        Fat supply quantity (g/capita/day)     309.54    320.74    309.09
        Feed                                  9903.00   9571.00  10668.00
        Food                                 63081.43  62785.33  63736.33
        Food supply (kcal/capita/day)        13483.00  13363.00  13288.00
        Food supply quantity (kg/capita/yr)   1555.77   1516.94   1509.28
        Import Quantity                      36736.08  36059.29  36238.29
        Losses                                7405.00   7428.00   7708.00
        Other uses (non-food)                 3400.17   3534.08   3970.08

In [84]:
file.groupby(['Area']).count()

,Area Code,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,,,
Algeria,1313,1313,1313,1313,1313,1313,1261,1268,1274,1279,1298
Angola,1424,1424,1424,1424,1424,1424,1378,1378,1388,1407,1396
Benin,1285,1285,1285,1285,1285,1285,1250,1260,1257,1253,1252
Botswana,1378,1378,1378,1378,1378,1378,1361,1369,1365,1368,1361
Burkina Faso,1409,1409,1409,1409,1409,1409,1382,1372,1392,1383,1373
Cabo Verde,1260,1260,1260,1260,1260,1260,1231,1229,1200,1193,1192
Cameroon,1460,1460,1460,1460,1460,1460,1450,1443,1443,1441,1432
Central African Republic,1344,1344,1344,1344,1344,1344,1300,1296,1314,1262,1308
Chad,1343,1343,1343,1343,1343,1343,1284,1303,1265,1281,1305
Comoros,45,45,45,45,45,45,45,45,45,45,45
Congo,1413,1413,1413,1413,1413,1413,1382,1377,1377,1395,1377
Côte d'Ivoire,1467,1467,1467,1467,1467,1467,1444,1447,1455,1454,1455
Djibouti,1095,1095,1095,1095,1095,1095,1052,1058,1054,1061,1040
Egypt,1488,1488,1488,1488,1488,1488,1461,1473,1470,1458,1468
Eswatini,1284,1284,1284,1284,1284,1284,1265,1240,1255,1251,1231
Ethiopia,1447,1447,1447,1447,1447,1447,1424,1430,1410,1428,1425
Ethiopia PDR,39,39,39,39,39,39,39,39,39,39,39
Gabon,1245,1245,1245,1245,1245,1245,1200,1202,1198,1206,1192
Gambia,1168,1168,1168,1168,1168,1168,1121,1115,1111,1116,1118
Ghana,1354,1354,1354,1354,1354,1354,1337,1333,1330,1333,1337
Guinea,1410,1410,1410,1410,1410,1410,1345,1349,1373,1383,1385
Guinea-Bissau,1128,1128,1128,1128,1128,1128,1044,1040,1054,1076,1091
Kenya,1560,1560,1560,1560,1560,1560,1544,1542,1540,1548,1548
Lesotho,1150,1150,1150,1150,1150,1150,1130,1097,1116,1110,1094
Liberia,1206,1206,1206,1206,1206,1206,1135,1134,1124,1135,1133
Madagascar,1439,1439,1439,1439,1439,1439,1416,1429,1431,1425,1424
Malawi,1447,1447,1447,1447,1447,1447,1416,1400,1394,1411,1410
Mali,1293,1293,1293,1293,1293,1293,1252,1256,1250,1243,1260
Mauritania,1195,1195,1195,1195,1195,1195,1106,1152,1119,1108,1170
Mauritius,1378,1378,1378,1378,1378,1378,1355,1352,1344,1340,1342
Morocco,1393,1393,1393,1393,1393,1393,1354,1381,1378,1369,1368
Mozambique,1427,1427,1427,1427,1427,1427,1396,1394,1401,1406,1400
Namibia,1283,1283,1283,1283,1283,1283,1274,1270,1266,1269,1256
Niger,1403,1403,1403,1403,1403,1403,1357,1367,1355,1365,1368
Nigeria,1474,1474,1474,1474,1474,1474,1470,1458,1460,1457,1456
Rwanda,1426,1426,1426,1426,1426,1426,1400,1378,1400,1397,1403
Sao Tome and Principe,1177,1177,1177,1177,1177,1177,1108,1125,1140,1122,1109
Senegal,1462,1462,1462,1462,1462,1462,1448,1449,1452,1452,1448
Seychelles,68,68,68,68,68,68,68,68,68,68,68
Sierra Leone,1242,1242,1242,1242,1242,1242,1177,1181,1188,1191,1197
South Africa,1399,1399,1399,1399,1399,1399,1394,1395,1395,1395,1396
Sudan,1316,1316,1316,1316,1316,1316,1277,1260,1271,1279,1268
Sudan (former),53,53,53,53,53,53,53,53,53,53,53
Togo,1294,1294,1294,1294,1294,1294,1219,1226,1243,1234,1266
Tunisia,1338,1338,1338,1338,1338,1338,1304,1318,1314,1314,1320
Uganda,1458,1458,1458,1458,1458,1458,1446,1446,1446,1435,1445
United Republic of Tanzania,1419,1419,1419,1419,1419,1419,1401,1405,1403,1409,1408
Zambia,1451,1451,1451,1451,1451,1451,1424,1420,1430,1425,1421
Zimbabwe,1393,1393,1393,1393,1393,1393,1374,1373,1358,1365,1356

In [85]:
#49 unique countries